### ISSUE TITLE
Cannot install by npm because of broken dependency

### ISSUE THREAD

**Issue by barbaracassani** [postaljs/monologue.js#11]
Doing 
`npm install monologue`
Stalls and timeouts apparently because of a broken dependency on a specific sha of riveter.js

  ` npm ERR! Command failed: Cloning into bare repository '/Users/barbaracassani/.npm/_git-remotes/git-github-com-ifandelse-riveter-git-c54a5909'...
npm ERR! fatal: unable to connect to github.com:`

**Comment by ifandelse** [comment]
Sorry for the trouble @barbaracassani! I will look into this and keep you posted.

**Comment by ifandelse** [comment]
@barbaracassani I haven't been able to reproduce the error you've described. From the error message is looks like npm wasn't able to connect to github at all - is this still an issue?

**Comment by barbaracassani** [comment]
Thank you @ifandelse , it seems all fine now -- it looks like it was a temporary connectivity issue. Intriguingly, all the other npm's installed just fine, it was an issue with that specific dependency. Interesting, but anyway the issue can be safely closed. Thank you for the quick reaction!
