### ISSUE TITLE
riveter causing install failure, behind corporate firewall

### ISSUE THREAD

**Issue by derickbailey** [postaljs/monologue.js#12]
Hey Jim,

I'm trying to install wascally... but installation fails because of monologue's dependency on riveter, at a specific commit: https://github.com/postaljs/monologue.js/blob/master/package.json#L56

The issue is a corporate web filter that I'm stuck behind, blocking the port for the "git://" protocol. I've got a ticket open to unblock this port... but until that happens, I'm dead in the water.

Would it be possible to update the monologue release to point to an NPM'd version of riveter? Or update the dependency to use "git+https://" instead of "git://"? 

Thanks, yo

  - Derick

**Comment by ifandelse** [comment]
@derickbailey - man I'm sorry! Yes, as soon as I get a chance I will publish the fork to npm and change the package.json. Might be a couple of hours as I'm stuck in an all-day meeting :-(

**Comment by ifandelse** [comment]
@derickbailey just bumped riveter to 0.2.0, and monologue to 0.3.4...wascally is allowing for patch ranges on monologue, so do you mind retrying it and seeing if this clears it up for you?

**Comment by derickbailey** [comment]
that got it! thanks, yo :) 
:+1:
